### ISSUE TITLE
NoReverseMatch when sorting in Django Admin using SortableForeignKey

### ISSUE THREAD

**Issue by kokhoor** [alsoicode/django-admin-sortable#174] opened 2017-09-13 11:17 UTC
When I am trying to sort my model PrePost in Django Admin (it is not an inline but has an admin itself), I received an error saying NoReverseMatch as below. Is sorting models with SortableForeignKey but not in InlineAdmin possible with django-admin-sortable?

Error:

NoReverseMatch at /admin/common/prepost/sort/
Reverse for 'common_prepost_do_sorting' with arguments '('',)' not found. 1 pattern(s) tried: [u'admin/common/prepost/sort/do-sorting/(?P<model_type_id>\\d+)/$']

The model is:

```
class PrePost(SortableMixin):
    module = SortableForeignKey(Module, related_name='module')
    name = models.CharField(max_length=128, db_index=False, verbose_name='method', help_text='pre_getOrder, post_getOrder')
    action = models.CharField(max_length=256, help_text='Method to call [app.class.method], e.g. order.utils.get_order')
    active_ind = models.BooleanField(default=True)
    order_no = models.PositiveIntegerField(default=0, editable=False)

    def __unicode__(self):
        return u'%s[#%d] %s' % (self.name, self.order_no, self.action)

    class Meta:
        verbose_name = u'PrePost'
        verbose_name_plural = u'PrePosts'
        ordering = ['order_no']
        index_together = [
            ['module', 'name', 'order_no']
        ]
```

And the traceback is:

```
Traceback (most recent call last):
  File "/Users/kokhoor/.virtualenvs/moonlight/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/kokhoor/.virtualenvs/moonlight/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/kokhoor/.virtualenvs/moonlight/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/kokhoor/.virtualenvs/moonlight/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/kokhoor/.virtualenvs/moonlight/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/kokhoor/.virtualenvs/moonlight/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 224, in inner
    return view(request, *args, **kwargs)
  File "/Users/kokhoor/.virtualenvs/moonlight/lib/python2.7/site-packages/adminsortable/admin.py", line 209, in sort_view
    return render(request, self.sortable_change_list_template, context)
  File "/Users/kokhoor/.virtualenvs/moonlight/lib/python2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/kokhoor/.virtualenvs/moonlight/lib/python2.7/site-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/Users/kokhoor/.virtualenvs/moonlight/lib/python2.7/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/Users/kokhoor/.virtualenvs/moonlight/lib/python2.7/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/Users/kokhoor/.virtualenvs/moonlight/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Users/kokhoor/.virtualenvs/moonlight/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Users/kokhoor/.virtualenvs/moonlight/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Users/kokhoor/.virtualenvs/moonlight/lib/python2.7/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/Users/kokhoor/.virtualenvs/moonlight/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Users/kokhoor/.virtualenvs/moonlight/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Users/kokhoor/.virtualenvs/moonlight/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Users/kokhoor/.virtualenvs/moonlight/lib/python2.7/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/Users/kokhoor/.virtualenvs/moonlight/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Users/kokhoor/.virtualenvs/moonlight/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Users/kokhoor/.virtualenvs/moonlight/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Users/kokhoor/.virtualenvs/moonlight/lib/python2.7/site-packages/django/template/loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "/Users/kokhoor/.virtualenvs/moonlight/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Users/kokhoor/.virtualenvs/moonlight/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Users/kokhoor/.virtualenvs/moonlight/lib/python2.7/site-packages/django/template/defaulttags.py", line 322, in render
    return nodelist.render(context)
  File "/Users/kokhoor/.virtualenvs/moonlight/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Users/kokhoor/.virtualenvs/moonlight/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Users/kokhoor/.virtualenvs/moonlight/lib/python2.7/site-packages/django/template/defaulttags.py", line 322, in render
    return nodelist.render(context)
  File "/Users/kokhoor/.virtualenvs/moonlight/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Users/kokhoor/.virtualenvs/moonlight/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Users/kokhoor/.virtualenvs/moonlight/lib/python2.7/site-packages/django/template/library.py", line 203, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "/Users/kokhoor/.virtualenvs/moonlight/lib/python2.7/site-packages/adminsortable/templatetags/adminsortable_tags.py", line 18, in render_nested_sortable_objects
    return render_to_string(sortable_nested_objects_template, context.flatten())
  File "/Users/kokhoor/.virtualenvs/moonlight/lib/python2.7/site-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/Users/kokhoor/.virtualenvs/moonlight/lib/python2.7/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/Users/kokhoor/.virtualenvs/moonlight/lib/python2.7/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/Users/kokhoor/.virtualenvs/moonlight/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Users/kokhoor/.virtualenvs/moonlight/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Users/kokhoor/.virtualenvs/moonlight/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Users/kokhoor/.virtualenvs/moonlight/lib/python2.7/site-packages/django/template/defaulttags.py", line 322, in render
    return nodelist.render(context)
  File "/Users/kokhoor/.virtualenvs/moonlight/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Users/kokhoor/.virtualenvs/moonlight/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Users/kokhoor/.virtualenvs/moonlight/lib/python2.7/site-packages/django/template/defaulttags.py", line 216, in render
    nodelist.append(node.render_annotated(context))
  File "/Users/kokhoor/.virtualenvs/moonlight/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Users/kokhoor/.virtualenvs/moonlight/lib/python2.7/site-packages/django/template/defaulttags.py", line 529, in render
    return self.nodelist.render(context)
  File "/Users/kokhoor/.virtualenvs/moonlight/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Users/kokhoor/.virtualenvs/moonlight/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Users/kokhoor/.virtualenvs/moonlight/lib/python2.7/site-packages/django/template/defaulttags.py", line 322, in render
    return nodelist.render(context)
  File "/Users/kokhoor/.virtualenvs/moonlight/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Users/kokhoor/.virtualenvs/moonlight/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Users/kokhoor/.virtualenvs/moonlight/lib/python2.7/site-packages/django/template/defaulttags.py", line 322, in render
    return nodelist.render(context)
  File "/Users/kokhoor/.virtualenvs/moonlight/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Users/kokhoor/.virtualenvs/moonlight/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Users/kokhoor/.virtualenvs/moonlight/lib/python2.7/site-packages/django/template/library.py", line 203, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "/Users/kokhoor/.virtualenvs/moonlight/lib/python2.7/site-packages/adminsortable/templatetags/adminsortable_tags.py", line 32, in render_object_rep
    return render_to_string(sortable_object_rep_template, context.flatten())
  File "/Users/kokhoor/.virtualenvs/moonlight/lib/python2.7/site-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/Users/kokhoor/.virtualenvs/moonlight/lib/python2.7/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/Users/kokhoor/.virtualenvs/moonlight/lib/python2.7/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/Users/kokhoor/.virtualenvs/moonlight/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Users/kokhoor/.virtualenvs/moonlight/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Users/kokhoor/.virtualenvs/moonlight/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Users/kokhoor/.virtualenvs/moonlight/lib/python2.7/site-packages/django/template/defaulttags.py", line 458, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Users/kokhoor/.virtualenvs/moonlight/lib/python2.7/site-packages/django/urls/base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/Users/kokhoor/.virtualenvs/moonlight/lib/python2.7/site-packages/django/urls/resolvers.py", line 497, in _reverse_with_prefix
    raise NoReverseMatch(msg)
```

**Comment by alsoicode** [comment] 2017-09-26 19:48
Sorry for the terrible delay getting back to you. I've been extremely busy over the past couple of weeks with a product launch at work.

The problem is that you're not passing in the content type id, referenced as `model_type_id` in the sortable mixin. The exception states:

> NoReverseMatch at /admin/common/prepost/sort/
> Reverse for 'common_prepost_do_sorting' **with arguments '('',)' not found**. 1 pattern(s) tried: [u'admin/common/prepost/sort/do-sorting/(?P<model_type_id>\d+)/$']

When you call `reverse()` be sure to supply the content type id value of your `PrePost` model and it should work as expected.

**Comment by alsoicode** [comment] 2017-10-11 11:05
Closing. If you still need help just let me know.

**Closed by alsoicode** 2017-10-11 11:05 UTC

**Comment by kokhoor** [comment] 2018-09-23 09:16
Thanks and sorry for late reply too. 

I believe it is because I was trying to use a SortableAdmin on a model with SortableForeignKey, thus causing the error. Changing the SortableForeignKey to ForeignKey will work, just the sorting are not grouped by the Foreign Key.

**Comment by jab3z** [comment] 2019-11-06 09:40
A very simple way to fix it is to to add this method on the parent model

```
@classmethod
def model_type_id(cls):
    return ContentType.objects.get_for_model(cls).id
