### ISSUE TITLE
not work in production mode

### ISSUE THREAD

**Issue by Mhs-220** [alsoicode/django-admin-sortable#201] opened 2018-09-08 11:42 UTC
hi
when i test it in my local host or with django runserver, it's work very well but when i use it with nginx and gunicorn, nothing happen
i check network and nothing post to my app
what can i do?

**Comment by alsoicode** [comment] 2018-09-08 19:33
There are no POST requests issued when dragging/dropping items in a change list? In Chrome Developer Tools, are there any JavaScript files returning 404s? Any console errors?

There's nothing specific in django-admin-sortable that would cause it not to work with nginx and gunicorn.

**Comment by Mhs-220** [comment] 2018-09-09 04:51
I check it as you said and its work on chrome very well!!!
but in firefox there is no 404 and there is nothing unloaded
i remove my cache too but that is not helped.
any idea?

**Comment by Mhs-220** [comment] 2018-09-09 12:14
i test it in another PC and its work well with firefox too, i can't understand it

**Comment by alsoicode** [comment] 2018-09-09 12:16
Working for me in Firefox 62. I've never had any previous reports of the sorting functionality not working in FireFox. Here's a screen recording from Firefox 62 on Windows 10.

[firefox.zip](https://github.com/alsoicode/django-admin-sortable/files/2364213/firefox.zip)

**Comment by alsoicode** [comment] 2018-09-14 00:26
I'm closing this for now, as it doesn't seem as if the problem is directly related. I'll re-open if you find something specific to the module code.

**Closed by alsoicode** 2018-09-14 00:26 UTC
